---
title: "Lesson Plan"
description: " "
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```




-----------------------------------------------------------------------------------------------
Week Date   Topic                                                                      Remarks
---- ------ -------------------------------------------------------------------------- ---------------------
1.   16/08  [Introduction to Geospatial Analytics](outline/Lesson01_outline.html)                

2.   23/08  [Geospatial Data Handling and Wrangling](outline/Lesson02_outline.html)          

3.   30/08  [Thematic and Analytical Mapping](outline/Lesson03_outline.html)         

4.   06/09  [Spatial Point Patterns Analysis](outline/Lesson04_outline.html)           Take-home Ex1 due

5.   13/09  [Advanced Spatial Point Patterns Analysis](outline/Lesson05_outline.html)

6.   20/09  [Spatial Weights and Applications](outline/Lesson06_outline.html)
        
7.   27/09  [Measures of Spatial Autocorrelation](outline/Lesson07_outline.html)       Take-home Ex2 due

8.   04/10  [Workshop on R Shiny](outline/workshop.html)                               Date: 6-7 October, 2021

9.   11/10  [Geographic Segmentation](outline/Lesson08_outline.html)

10.  18/10  [Geographically Weighted Regression](outline/Lesson09_outline.html)        

11.  25/10  [Modelling Geographic of Accessibility](outline/Lesson10_outline.html)                 Take-home Ex3 due

12.  01/11  [Spatial Interaction Models](outline/Lesson11_outline.html)

13.  08/11  Epilogue

14.  15/11  Townhall Presentation                                                      Shiny4GA Project due

15   22/11  Exam week
----------------------------------------------------------------






