---
title: "Lesson 10: Modelling Geographic of Accessibility"
description: |
  A new article created using the Distill format.
output:
  distill::distill_article:
    toc: true
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Content
- Basic Concepts of Geographic Accessibility
- Gravitational Law and Distance Decay Function
- Introducing Potential Models
    - The classic model
- Hansen Potential Accessibility Model
- Two-step Floating Catchment Area (2SFCA) Method 
- Kernel Density Two-Step Floating Catchment Area (KD2SFCA) Method
- Interpreting and Visualising Modelling Results

## Meet-up Slides and Hands-on Notes 

Slides and hands-on notes in [html](Topics/Topic03/Topic04.html) and [pdf](Topics/Topic03/Topic04.pdf) formats


## Self-reading Before Meet-up

Read before lesson:

- Long, J. (2017). Modelling Accessibility. The Geographic Information Science & Technology Body of Knowledge (3rd Quarter 2017 Edition), John P. Wilson (ed.). DOI: 10.22224/gistbok/2017.3.7
- Hansen, W. G. (1959): “How Accessibility Shapes Land Use”. Journal of the American Institute of Planners, 25, 2, p. 73-76.
- Luo, W.; Wang, F. (2003) "Measures of spatial accessibility to health care in a GIS environment: synthesis and a case study in the Chicago region". Environment and Planning B: Planning and Design. 30 (6): 865–884. doi:10.1068/b29120.
- Luo, W.; Qi, Y. (2009). "An enhanced two-step floating catchment area (E2SFCA) method for measuring spatial accessibility to primary care physicians". Health & Place. 15 (4): 1100–1107.

## Reference
- Section on “Transportation and Accessibility” in The Geography of Transport Systems.
- Rich, D.C. (1980) Potential Models in Human Geography.
- Orpana, T./Lampinen, J. (2003) “Building spatial choice models from aggregate data”. Journal of Regional Science,43, 2, p. 319-347.
- Two-step floating catchment area method.
- Cheng, Gang et. al. (2016) “Spatial difference analysis for accessibility to high level hospitals based on travel time in Shenzhen, China” Habitat International, Vol.53, p.485-494.
- Polzin, Pierre ; Borges, José ; Coelho, António  (2014) “An Extended Kernel Density Two-Step Floating Catchment Area Method to Analyze Access to Health Care” Environment and planning. B, Planning & design, Vol.41 (4), p.717-735.     

## All About R:
- hansen() function in REAT package.
- ac() function in SpatialAcc package.







